#! /usr/bin/env bash

line.map(){
    local line
    while read -rd $'\n' line; do
        eval "$@"
    done
}

# using regex to filter
line.rmap(){
    local line
    local code="${2: echo \"\$line\"}"
    while read -rd $'\n' line; do
        if echo "$line" | grep "$1"; then
            eval "$code"
        fi
    done
}

# using glob to filter
line.gmap(){
    local line
    local code="${2: echo \"\$line\"}"
    while read -rd $'\n' line; do
        if echo "$line" | grep "$1"; then
            eval "$code"
        fi
    done
}

# using eval to filter
line.fmap(){
    local line
    local code="${2: echo \"\$line\"}"
    while read -rd $'\n' line; do
        if eval "$1"; then
            eval "$code"
        fi
    done
}


line.to_array(){
    local name=${1:?Array name}
    local line
    while read -r line; do
        eval "$name+=( \"$line\" )"
    done
}

str.trim(){
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    echo -n "$var"
}

line.to_array.trim(){
    local name=${1:?Array name}
    local line
    while read -r line; do
        line="$(str.trim "$line")"
        eval "$name+=( \"$line\" )"
    done
}

line.to_array.trim.ignore_empty(){
    local name=${1:?Array name}
    local line
    while read -r line; do
        line="$(str.trim "$line")"
        [ "$line" = "" ] && continue

        eval "$name+=( \"$line\" )"
    done
}
